# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Varisty' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Varisty

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Nuke'

  target 'VaristyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VaristyUITests' do
    # Pods for testing
  end

end
